### ISSUE TITLE
got an error (Duplicate entry name: adapter1.class)

### ISSUE THREAD

**Issue by dingjibang** [F43nd1r/rhino-android#3]
java.util.zip.ZipException: Duplicate entry name: adapter1.class
     at java.util.zip.ZipFile.readCentralDir(ZipFile.java:452)
     at java.util.zip.ZipFile.<init>(ZipFile.java:175)
     at java.util.zip.ZipFile.<init>(ZipFile.java:131)
     at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
     at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
     at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
     at com.android.dx.command.dexer.Main.processOne(Main.java:672)
     at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
     at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
     at com.android.dx.command.dexer.Main.run(Main.java:277)
     at com.faendir.rhino_android.AndroidClassLoader.dexJar(AndroidClassLoader.java:103)
     at com.faendir.rhino_android.AndroidClassLoader.defineClass(AndroidClassLoader.java:64)
     at org.mozilla.javascript.JavaAdapter.loadAdapterClass(JavaAdapter.java:535)
     at org.mozilla.javascript.JavaAdapter.getAdapterClass(JavaAdapter.java:333)
     at org.mozilla.javascript.JavaAdapter.js_createAdapter(JavaAdapter.java:173)
     ......

Hello! first, thx your project!

I'm making a game and using JS to create game UI, when I enter (RhinoAndroidHelper.enter()) the context and create the first JavaAdapter, it works, but when I exit() the context and sometimes re-enter context and create another JavaAdapter, it's throw an Exception like above.

And this script on desktop-java is works.

PS: I created first JavaAdapter and it extend A.class, and second JavaAdapter extend B.class, when I creating second JavaAdapter(B.class), it's seem like still create an Adapter extend A.class, just like somethings not clear after first create. (im sorry for my bad English...)

**Comment by F43nd1r** [comment]
Possible fix afc6b55a8602bc52e541549e25ea1b669249b474

**Comment by dingjibang** [comment]
thx!

**Comment by F43nd1r** [comment]
If you could confirm that it works, I'll build a release

**Comment by dingjibang** [comment]
sorry, it still doesn't work

**Comment by dingjibang** [comment]
wait a minute

**Comment by dingjibang** [comment]
yes, still doesn't work

**Comment by F43nd1r** [comment]
Okay, can you give some more context? At best code to reproduce.

**Comment by dingjibang** [comment]
We have a class A

    public class A {
        public static void createB(){
            Context ctx = Game.getJSContext();
            ScriptableObject scope = ctx.initStandardObjects(null, true);
            Object obj = ctx.evaluateString(scope, "new JavaAdapter(" + B.class.getName() + ", {})", null, 1, null);
            B adapter = (B)Context.jsToJava(obj, B.class);//THROW EXCEPTION
            Context.exit();
        }
    
        public void create() { }
    }

and blank class B:

    public class B {}

and main:

	Context ctx = Game.getJSContext();
	ScriptableObject scope = ctx.initStandardObjects(null, true);
	Object obj = ctx.evaluateString(scope, "new JavaAdapter(" + A.class.getName() + ", {create: function(){"+A.class.getName() +".createB()}})", null, 1, null);
	A adapter = (A)Context.jsToJava(obj, A.class);
	Context.exit();
	adapter.create();


the A.createB() is called by JS(not java, it's working if java)

It may be too complicated, if you feel a lot of trouble, don‘t need to resolve

**Comment by F43nd1r** [comment]
Okay, so I identified the problem: Both Adapter classes are called `adapter1`, this makes it impossible to load the second class. However, I'm not sure why that is the case.

**Comment by F43nd1r** [comment]
Okay, I have tested this with normal java. The classes are also named adapter1, so the problem exists too. I'm unsure why it still works, but I guess the default classloader just overwrites the already loaded class. In android this is not possible. I suggest you try to use only one Context and only one Scope (at once), that should eliminate the problem.

**Comment by dingjibang** [comment]
thx!
